docs: >-
  Manage app clients, and perform authentication operations for admin-level
  access control
imports:
  root: __package__.yml
service:
  auth: false
  url: Default
  display-name: Application Clients
  base-path: ''
  endpoints:
    list:
      method: GET
      display-name: List App Clients
      path: /v2/app_clients
      auth: true
      request:
        name: ApplicationClientsListRequest
        query-parameters:
          limit:
            type: optional<integer>
            docs: The maximum number of App Clients to return at one time.
          filter:
            type: optional<string>
            docs: Regular expression to filter the names of the App Clients.
          page_key:
            type: optional<string>
            docs: >-
              Used to retrieve the next page of App Clients after the limit has
              been reached.
      response:
        docs: An array of App Clients.
        type: root.ListAppClientsResponse
      errors:
        - root.BadRequestError
        - root.ForbiddenError
      examples:
        - response:
            body:
              app_clients:
                - id: id
                  name: name
                  description: description
                  client_id: client_id
                  client_secret: client_secret
                  api_roles:
                    - owner
                  api_policy:
                    name: name
                    allowed_operations:
                      allowed_operations:
                        allow_any_resource: true
              metadata:
                page_key: page_key
    get:
      method: GET
      display-name: Get an App Client
      path: /v2/app_clients/{app_client_id}
      path-parameters:
        app_client_id:
          type: string
          docs: The name of the App Client.
      auth: true
      response:
        docs: The App Client.
        type: root.AppClient
      errors:
        - root.ForbiddenError
      examples:
        - path-parameters:
            app_client_id: app_client_id
          response:
            body:
              id: id
              name: name
              description: description
              client_id: client_id
              client_secret: client_secret
              api_roles:
                - owner
              api_policy:
                name: name
                allowed_operations:
                  allowed_operations:
                    allow_any_resource: true
    delete:
      method: DELETE
      display-name: Delete an App Client
      path: /v2/app_clients/{app_client_id}
      path-parameters:
        app_client_id:
          type: string
          docs: The name of App Client.
      auth: true
      errors:
        - root.ForbiddenError
      examples:
        - path-parameters:
            app_client_id: app_client_id
    update:
      method: PATCH
      display-name: Update an App Client
      path: /v2/app_clients/{app_client_id}
      path-parameters:
        app_client_id:
          type: string
          docs: The name of App Client.
      auth: true
      request:
        name: UpdateAppClientRequest
        body:
          properties:
            description:
              type: optional<string>
              docs: The new App Client description.
            api_roles:
              type: optional<list<root.ApiRole>>
              docs: >-
                The new roles attached to the App Client. These roles will
                replace the current roles.
      response:
        docs: The App Client.
        type: root.AppClient
      errors:
        - root.ForbiddenError
      examples:
        - path-parameters:
            app_client_id: app_client_id
          request: {}
          response:
            body:
              id: id
              name: name
              description: description
              client_id: client_id
              client_secret: client_secret
              api_roles:
                - owner
              api_policy:
                name: name
                allowed_operations:
                  allowed_operations:
                    allow_any_resource: true
